// Code generated by "stringer -type=ByteOrder -output=byte_order_string.go"; DO NOT EDIT.

package runtimeutil

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LittleEndian-0]
	_ = x[BigEndian-1]
}

const _ByteOrder_name = "LittleEndianBigEndian"

var _ByteOrder_index = [...]uint8{0, 12, 21}

func (i ByteOrder) String() string {
	if i < 0 || i >= ByteOrder(len(_ByteOrder_index)-1) {
		return "ByteOrder(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ByteOrder_name[_ByteOrder_index[i]:_ByteOrder_index[i+1]]
}
