// Code generated by "stringer -type=StructKeyType -output=struct_key_type_string.go"; DO NOT EDIT.

package msgpack

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StructKeyTypeInt-0]
	_ = x[StructKeyTypeString-1]
}

const _StructKeyType_name = "StructKeyTypeIntStructKeyTypeString"

var _StructKeyType_index = [...]uint8{0, 16, 35}

func (i StructKeyType) String() string {
	if i >= StructKeyType(len(_StructKeyType_index)-1) {
		return "StructKeyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StructKeyType_name[_StructKeyType_index[i]:_StructKeyType_index[i+1]]
}
