name: CI

on:
  [pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-18.04
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "setup Go"
        uses: actions/setup-go@v2
        with:
          stable: true
          go-version: '^1.16'
      - name: "go test"
        run: |
          go test ./...

  test-macos:
    runs-on: macos-10.15
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "setup Go"
        uses: actions/setup-go@v2
        with:
          stable: true
          go-version: '^1.16'
      - name: "go test"
        run: |
          go test ./...

  test-windows:
    runs-on: windows-2019
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "setup Go"
        uses: actions/setup-go@v2
        with:
          stable: true
          go-version: '^1.16'
      - name: "go test"
        run: |
          go test ./...