name: CI

on:
  [push]

jobs:

  test:
    name: "Test"
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Set up git config"
        run: |
          git config --global core.autocrlf false
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          stable: true
          go-version: '^1.17'
      - name: "Test"
        run: |
          go test -cover ./...

  benchmark:
    name: "Benchmark"
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Set up git config"
        run: |
          git config --global core.autocrlf false
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          stable: true
          go-version: '^1.17'
      - name: "Benchmark"
        run: |
          go test -bench . ./...
