name: CI

on:
  [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "setup Go"
        uses: actions/setup-go@v2
        with:
          stable: true
          go-version: '^1.16'
      - name: "go test"
        run: |
          go test ./...
